# Generated by Django 5.2.5 on 2025-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bridge_width_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bridge width (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, help_text='e.g. 2025 FALL Collection', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_width_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Frame front (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_features',
            field=models.TextField(blank=True, help_text='e.g. Lenses Block Blue Light and 99.9% of UV Rays'),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_height_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Lens height (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_type',
            field=models.CharField(blank=True, help_text='e.g. Clear Lenses', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_width_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Lens width (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='temple_length_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temple length (mm)'),
        ),
    ]
